name: Publish Container to Docker Packages

# Documentation on the primary Action used here: https://github.com/marketplace/actions/publish-docker

on:
  release:
      types: [published]
  push:
      branches:
        - development
jobs:
  publish_release:
    runs-on: ubuntu-latest
    steps:
    - name: Reclaim space
      run: |
            sudo rm -rf /usr/share/dotnet
            sudo rm -rf /opt/ghc
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: mlf-core/liver_ct_segmentation
        username: mlf-core
        password: '${{ secrets.MLF_CORE_SYNC_TOKEN}}'
        registry: ghcr.io
        tags: "latest,1.0.0"

